import { useEffect, useState } from "react";
import { CheckCircle2, Scale, WalletCards } from "lucide-react";
import MetricCard from "../components/MetricCard";
import { recoveryDemo } from "../services/recoveryDemo";
import type { RecoveryBenchmark } from "../types/recovery";

const rupees = (value: number) => `₹${value.toLocaleString("en-IN")}`;
export default function BenchmarkPage() {
  const [data, setData] = useState<RecoveryBenchmark | null>(null);
  useEffect(() => { recoveryDemo.getBenchmark().then(setData); }, []);
  if (!data) return <div className="p-6 text-[#3d2b1f]/70 font-semibold">Running synthetic benchmark…</div>;
  return <div className="space-y-6"><div><div className="inline-flex rounded-full bg-[#faedcd] px-3 py-1 text-xs font-black tracking-wider text-[#8b572f]">{data.label.toUpperCase()} · DEMO DATA</div><h1 className="mt-3 text-3xl font-black text-[#2d1e18] font-display">DuesPilot vs Baseline</h1><p className="mt-1 text-[#3d2b1f]/70">A transparent comparison generated from the same fictional batch.</p></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><MetricCard label="₹ at Risk" value={rupees(data.amount_at_risk)} icon={<WalletCards />} /><MetricCard label="Net Recovered Value" value={rupees(data.net_recovered_value)} icon={<CheckCircle2 />} /><MetricCard label="Average Contacts" value={data.average_contacts} icon={<Scale />} /></div><div className="overflow-x-auto rounded-lg border border-[#faedcd]"><table className="w-full text-left"><thead className="bg-[#faedcd]/60 text-xs uppercase tracking-wider"><tr><th className="px-5 py-4">Measure</th><th className="px-5 py-4">Baseline</th><th className="px-5 py-4">DuesPilot</th></tr></thead><tbody className="bg-white/60"><tr className="border-t border-[#faedcd]"><td className="px-5 py-4 font-bold">Recovery approach</td><td className="px-5 py-4">One generic reminder</td><td className="px-5 py-4">Risk + diagnosis + approved action + bounded workflow</td></tr><tr className="border-t border-[#faedcd]"><td className="px-5 py-4 font-bold">Amount recovered</td><td className="px-5 py-4">{rupees(data.baseline_recovered)}</td><td className="px-5 py-4 font-bold text-emerald-800">{rupees(data.sambhaash_recovered)}</td></tr><tr className="border-t border-[#faedcd]"><td className="px-5 py-4 font-bold">Recovery rate</td><td className="px-5 py-4">{data.baseline_recovery_rate}%</td><td className="px-5 py-4 font-bold text-emerald-800">{data.recovery_rate}%</td></tr><tr className="border-t border-[#faedcd]"><td className="px-5 py-4 font-bold">Escalations / promises</td><td className="px-5 py-4">Not modeled</td><td className="px-5 py-4">{data.escalations} escalations · {data.promise_to_pay_count} promises</td></tr></tbody></table></div><p className="text-xs text-[#3d2b1f]/60">Assumption model: {data.assumption_model}</p></div>;
}
