import { useEffect, useState } from "react";
import { BarChart3, Play, ShieldCheck } from "lucide-react";
import { recoveryDemo } from "../services/recoveryDemo";
import { useDemoAuth } from "../services/demoAuth";

export default function DiagnosisEvaluationPage() {
  const { user } = useDemoAuth(); const isAdmin = user?.role === "admin";
  const [result, setResult] = useState<any | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { recoveryDemo.getEvaluation().then(setResult); }, []);
  const run = async () => { setBusy(true); try { setResult(await recoveryDemo.runEvaluation()); } finally { setBusy(false); } };
  return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><div className="inline-flex rounded-full bg-violet-100 px-3 py-1 text-xs font-black tracking-wider text-violet-700">MEASURED AI EVALUATION · SYNTHETIC DATA</div><h1 className="mt-3 text-3xl font-black text-[#2d1e18] font-display">Diagnosis evaluation</h1><p className="mt-1 max-w-3xl text-[#3d2b1f]/70">A reproducible 60-reply test set checks whether the diagnosis layer identifies the expected recovery cause. It does not claim real merchant performance.</p></div>{isAdmin && <button disabled={busy} onClick={run} className="flex items-center justify-center gap-2 rounded-lg bg-violet-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-50"><Play size={17} />{busy ? "Running 60 cases…" : "Run evaluation"}</button>}</div>{!result ? <section className="rounded-xl border border-[#faedcd] bg-white/70 p-10 text-center"><BarChart3 className="mx-auto text-[#8b572f]" size={36} /><h2 className="mt-4 text-xl font-black text-[#2d1e18] font-display">No result saved yet</h2><p className="mt-2 text-sm text-[#3d2b1f]/65">{isAdmin ? "Run the 60-case synthetic evaluation to generate a reproducible result." : "An administrator can run and save the evaluation result."}</p></section> : <><div className="grid gap-4 md:grid-cols-4"><Metric label="Synthetic replies" value={result.total_cases} /><Metric label="Correct classifications" value={result.correct} /><Metric label="Accuracy" value={`${result.accuracy}%`} /><Metric label="Fallbacks" value={result.fallback_count} /></div><section className="rounded-xl border border-[#faedcd] bg-white/70 p-6"><div className="flex items-center gap-2"><ShieldCheck className="text-violet-700" /><h2 className="text-xl font-black text-[#2d1e18] font-display">Per-cause results</h2></div><p className="mt-3 text-xs text-[#3d2b1f]/60">Sources: {Object.entries(result.sources || {}).map(([source, count]) => `${source}: ${count}`).join(" · ")}</p><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{Object.entries(result.per_class).map(([cause, value]: [string, any]) => <div key={cause} className="rounded-lg border border-[#faedcd] bg-[#fefae0] p-4"><p className="font-bold capitalize text-[#2d1e18]">{cause}</p><p className="mt-2 text-2xl font-black text-violet-700">{value.accuracy}%</p><p className="text-xs text-[#3d2b1f]/60">{value.correct}/{value.total} correct</p></div>)}</div><p className="mt-5 text-xs text-[#3d2b1f]/55">{result.disclaimer}</p></section></>}</div>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-[#faedcd] bg-white/70 p-5"><p className="text-xs font-black uppercase tracking-wider text-[#8b572f]">{label}</p><p className="mt-2 text-3xl font-black text-[#2d1e18]">{value}</p></div>; }
