import { useEffect, useState } from "react";
import { BarChart3, CheckCircle2, PhoneCall, ShieldAlert, TrendingUp, WalletCards } from "lucide-react";
import MetricCard from "../components/MetricCard";
import { recoveryDemo } from "../services/recoveryDemo";
import type { RecoveryBenchmark, RecoverySummary } from "../types/recovery";

const rupees = (value: number) => `₹${value.toLocaleString("en-IN")}`;

export default function RecoveryAnalyticsPage() {
  const [benchmark, setBenchmark] = useState<RecoveryBenchmark | null>(null);
  const [live, setLive] = useState<RecoverySummary | null>(null);
  useEffect(() => { Promise.all([recoveryDemo.getBenchmark(), recoveryDemo.getSummary()]).then(([batch, current]) => { setBenchmark(batch); setLive(current); }); }, []);
  if (!benchmark || !live) return <div className="p-6 text-[#3d2b1f]/70 font-semibold">Calculating recovery analytics…</div>;
  return <div className="space-y-6">
    <div><div className="inline-flex rounded-full bg-[#faedcd] px-3 py-1 text-xs font-black tracking-wider text-[#8b572f]">DEMO DATA · LIVE OUTCOMES + SYNTHETIC BENCHMARK</div><h1 className="mt-3 text-3xl font-black text-[#2d1e18] font-display">Recovery Analytics</h1><p className="mt-1 text-[#3d2b1f]/70">Live demo outcomes update when a recovery call is completed; the benchmark remains a separate reproducible comparison.</p></div>
    <section className="rounded-lg border border-emerald-200 bg-emerald-50/70 p-6"><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-black tracking-wider text-emerald-800">LIVE DEMO OUTCOMES</p><h2 className="mt-1 text-xl font-black text-[#2d1e18] font-display">{live.recovered_revenue ? `${rupees(live.recovered_revenue)} recovered in this demo run` : "No payment recovered in this demo run yet"}</h2></div><p className="text-sm text-emerald-900/75">Updates from the same stateful recovery workflow and call summaries.</p></div><div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Recovered Revenue" value={rupees(live.recovered_revenue)} icon={<WalletCards />} trend="up" trendValue={`${live.recovery_rate}% current recovery rate`} /><MetricCard label="Revenue Still at Risk" value={rupees(live.revenue_at_risk)} icon={<TrendingUp />} /><MetricCard label="Active Promises" value={live.promise_to_pay} icon={<PhoneCall />} /><MetricCard label="Escalations" value={live.escalations} icon={<ShieldAlert />} /></div>{live.recovered_revenue > 0 && <div className="mt-5 flex items-center gap-2 rounded-lg border border-emerald-200 bg-white/70 px-4 py-3 text-sm font-semibold text-emerald-900"><CheckCircle2 size={18} />Payment confirmation is reflected here and further outreach is stopped by policy.</div>}</section>
    <section className="glass rounded-lg border border-[#faedcd]/60 p-6"><div className="flex items-center gap-2"><BarChart3 className="text-[#8b572f]" /><h2 className="text-xl font-black text-[#2d1e18] font-display">Synthetic batch benchmark</h2></div><p className="mt-3 max-w-4xl text-sm leading-6 text-[#3d2b1f]/75">{benchmark.assumption_model}</p><div className="mt-5 grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4"><MetricCard label="Invoices Evaluated" value={benchmark.invoices_evaluated} icon={<BarChart3 />} /><MetricCard label="Batch Amount at Risk" value={rupees(benchmark.amount_at_risk)} icon={<TrendingUp />} /><MetricCard label="Batch Promises" value={benchmark.promise_to_pay_count} icon={<PhoneCall />} /><MetricCard label="Batch Escalations" value={benchmark.escalations} icon={<ShieldAlert />} /></div><div className="mt-6 grid md:grid-cols-2 gap-5"><div className="rounded-lg bg-[#faedcd]/40 p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#3d2b1f]/65">Baseline — one generic reminder</p><p className="mt-2 text-3xl font-black text-[#2d1e18]">{rupees(benchmark.baseline_recovered)}</p><p className="text-sm text-[#3d2b1f]/65">{benchmark.baseline_recovery_rate}% recovery rate</p></div><div className="rounded-lg bg-emerald-50 border border-emerald-100 p-5"><p className="text-xs font-bold uppercase tracking-wider text-emerald-800/70">DuesPilot — bounded adaptive workflow</p><p className="mt-2 text-3xl font-black text-emerald-800">{rupees(benchmark.duespilot_recovered)}</p><p className="text-sm text-emerald-800/75">{benchmark.recovery_rate}% recovery rate · {rupees(benchmark.improvement)} incremental recovery</p></div></div></section>
  </div>;
}
